### ISSUE TITLE
Ship with TypeScript typings?

### ISSUE THREAD

**Issue by someone1** [jemmyphan/supafetch#1]
I made one for myself so thought I'd share it here in case you want to ship it with the package. I'm not sure how to submit this to DefinitelyTyped so I'd see if you're open to including it here before I attempt that.

```typescript
declare interface InterceptorFunc {
  (options: object): object;
}
declare interface ResponseFunc {
  (response: SupaResult): SupaResult;
}
declare interface SupaResult {
  request: Request;
  response: Response;
  data: any;
}

declare class Supafetch {
  private baseURL: string;
  private headers: { [key: string]: string };
  private interceptors: { request: InterceptorFunc; responseSuccess: ResponseFunc; responseFail: ResponseFunc };

  constructor();
  setBaseUrl(value: string): void;
  setDefaultheaders(headers?: { [key: string]: string }): void;
  setRequestInterceptor(interceptor: InterceptorFunc): void;
  setResponseInterceptor(success: ResponseFunc, fail: ResponseFunc): void;
  _request(url: string, options?: RequestInit): Promise<SupaResult>;

  get(url: string, options: RequestInit): Promise<SupaResult>;
  post(url: string, options: RequestInit): Promise<SupaResult>;
  delete(url: string, options: RequestInit): Promise<SupaResult>;
  put(url: string, options: RequestInit): Promise<SupaResult>;
  patch(url: string, options: RequestInit): Promise<SupaResult>;
}

declare module 'supafetch' {
  const supafetch: Supafetch;
  export default supafetch;
}
```

**Comment by jemmyphan** [comment]
looks good, i'll include this definitely. thanks anyway

**Comment by someone1** [comment]
My apologies, it just occurred to me that maybe `InterceptorFunc` should be defined as follows?

```typescript
declare interface InterceptorFunc {
  (options: RequestInit): RequestInit;
}
```
This just defines the expected parameter/response types more accurately.

**Comment by someone1** [comment]
Sorry, I found a little typo: `setDefaultheaders` should be `setDefaultHeaders`

It also seems this isn't valid to use with typescript since [you modify](https://github.com/jemmyphan/supafetch/blob/master/src/index.js#L83) what should be readonly (the response) according to typescript definitions. I have my target set to ES5

`TypeError: Cannot assign to read only property 'headers' of object '#<Response>'`

Is there a reason you copy out the headers only to reassign them?

**Comment by jemmyphan** [comment]
i used to have a format problem in react-native, that's why i reassigned it.
I'm thinking of rewriting it to typescript while taking this headers matter into account and adding #2.
hopefully i can make it in near time.

also you may have a look at https://github.com/niftylettuce/frisbee
it's better in many ways.

**Comment by someone1** [comment]
Frisbee is nice but it doesn't have a `fetch` compatible API surface. I have a need to use something `fetch` compatible for things like API keys and such, but frisbee only offers the HTTP verb options. I guess I could write a small wrapper around frisbee to make it compatible....

I'll look into it and give it a try, this package looked lightweight and simple enough for my needs.
